engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  shellcheck:
    enabled: true
ratings:
  paths:
  - bin/
  - lib/**/*.js
exclude_paths:
- "node_modules/**"
- "test/**"
- "integration/**"
